/*
 * Cognigy Demo Studio — filesystem layout.
 * SE data lives OUTSIDE the app install, so app updates never touch demos:
 *   ~/CognigyDemoStudio/
 *     demos/<slug>/   demo.json + index.html + src/ + dist/ + locked/
 *     settings.json
 */
const os = require("os");
const path = require("path");
const fs = require("fs");

const DATA_ROOT = process.env.CDS_DATA_DIR || path.join(os.homedir(), "CognigyDemoStudio");
const DEMOS_ROOT = path.join(DATA_ROOT, "demos");
const SETTINGS_FILE = path.join(DATA_ROOT, "settings.json");
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const TEMPLATES_ROOT = path.join(REPO_ROOT, "templates");
const SHARED_ROOT = path.join(REPO_ROOT, "packages", "shared");

function ensureDirs() {
  fs.mkdirSync(DEMOS_ROOT, { recursive: true });
}

function demoDir(slug) {
  // Slugs are generated by the store; belt-and-braces against traversal.
  if (!/^[a-z0-9][a-z0-9-]*$/.test(slug)) throw new Error("Bad demo id: " + slug);
  return path.join(DEMOS_ROOT, slug);
}

module.exports = { DATA_ROOT, DEMOS_ROOT, SETTINGS_FILE, REPO_ROOT, TEMPLATES_ROOT, SHARED_ROOT, ensureDirs, demoDir };
