/*
 * Cognigy Demo Studio — double-click launchers, and start-at-login.
 *
 * WHY THIS EXISTS
 *
 * main.js opens by claiming "SEs launch the app like any other program — no
 * terminal, ever (SOW §2)". This is the file that makes that true. After the
 * one-time `npm install`, launching needs ONLY the Electron binary — no Node,
 * no npm, no shell, and on Windows no console window:
 *
 *   macOS    node_modules/electron/dist/Electron.app/Contents/MacOS/Electron <repo>
 *   Windows  node_modules\electron\dist\electron.exe                         <repo>
 *
 * The launchers are GENERATED ON THE SE'S OWN MACHINE, by the postinstall
 * hook. That is not just convenient, it is the whole reason this beats
 * shipping an unsigned .dmg/.exe: a locally created bundle never carries the
 * com.apple.quarantine attribute, so there is no Gatekeeper prompt on macOS
 * and no SmartScreen warning on Windows. A downloaded unsigned installer would
 * have both.
 *
 * No Electron imports here — postinstall runs this under plain Node.
 */
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const APP_NAME = "Cognigy Demo Studio";
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const ASSETS = path.join(REPO_ROOT, "assets");
const IS_MAC = process.platform === "darwin";
const IS_WIN = process.platform === "win32";

/* ── where the Electron binary lives ─────────────────────────────────────── */

function electronBinary() {
  const dist = path.join(REPO_ROOT, "node_modules", "electron", "dist");
  const rel = IS_MAC
    ? path.join("Electron.app", "Contents", "MacOS", "Electron")
    : "electron.exe";
  const p = path.join(dist, rel);
  return fs.existsSync(p) ? p : null;
}

/* ── destinations ────────────────────────────────────────────────────────── */

function desktopDir() {
  const d = path.join(os.homedir(), "Desktop");
  return fs.existsSync(d) ? d : null;
}

function appMenuDir() {
  if (IS_MAC) return path.join(os.homedir(), "Applications");
  return path.join(process.env.APPDATA || "", "Microsoft", "Windows", "Start Menu", "Programs");
}

function startupDir() {
  if (IS_MAC) return null; // macOS uses System Events login items, not a folder
  return path.join(process.env.APPDATA || "", "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
}

/** The launcher the login item should point at — the app-menu copy. */
function primaryLauncher() {
  const dir = appMenuDir();
  if (!dir) return null;
  return path.join(dir, APP_NAME + (IS_MAC ? ".app" : ".lnk"));
}

/* ── macOS: a .app bundle is just a folder ───────────────────────────────── */

function plist() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>ai.cognigy.demostudio.launcher</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>${version()}</string>
  <key>CFBundleShortVersionString</key><string>${version()}</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSMicrophoneUsageDescription</key><string>Demo Studio uses the microphone for Cognigy voice demos.</string>
</dict>
</plist>
`;
}

/*
 * Everything is quoted because the repo path very often contains spaces, and
 * REPO is embedded rather than derived: a launcher must keep working no matter
 * what directory Finder happens to start it from.
 */
function macScript(electron) {
  return `#!/bin/sh
# Generated by ${APP_NAME}. Do not edit — regenerate with: npm run setup
REPO=${shq(REPO_ROOT)}
ELECTRON=${shq(electron)}

if [ ! -x "$ELECTRON" ]; then
  osascript -e 'display alert "${APP_NAME} can’t start" message "Its files have moved or npm install has not been run.\\n\\nOpen the project folder in Terminal and run:  npm install" as critical'
  exit 1
fi

exec "$ELECTRON" "$REPO" "$@"
`;
}

/** Single-quote for /bin/sh, the only safe way to carry an arbitrary path. */
function shq(s) {
  return "'" + String(s).replace(/'/g, "'\\''") + "'";
}

function writeMacApp(dest, electron) {
  fs.rmSync(dest, { recursive: true, force: true });
  const contents = path.join(dest, "Contents");
  fs.mkdirSync(path.join(contents, "MacOS"), { recursive: true });
  fs.mkdirSync(path.join(contents, "Resources"), { recursive: true });
  fs.writeFileSync(path.join(contents, "Info.plist"), plist());
  fs.writeFileSync(path.join(contents, "MacOS", "launcher"), macScript(electron), { mode: 0o755 });
  const icns = path.join(ASSETS, "icon.icns");
  if (fs.existsSync(icns)) fs.copyFileSync(icns, path.join(contents, "Resources", "icon.icns"));
  // Finder caches bundle metadata; touching the bundle makes it re-read the icon.
  try { execFileSync("touch", [dest]); } catch (e) {}
}

/* ── Windows: .lnk via WScript.Shell ─────────────────────────────────────── */

/*
 * TargetPath is electron.exe itself, NOT electron.cmd — the .cmd goes through
 * cmd.exe and flashes a console window on every launch.
 *
 * The PowerShell goes through a temp .ps1 rather than -Command: repo paths
 * contain spaces and often apostrophes, and quoting those through a single
 * -Command string is where this breaks.
 */
function writeWinShortcut(dest, electron, args) {
  const ico = path.join(ASSETS, "icon.ico");
  const ps = [
    "$ErrorActionPreference = 'Stop'",
    "$s = (New-Object -ComObject WScript.Shell).CreateShortcut(" + psq(dest) + ")",
    "$s.TargetPath = " + psq(electron),
    "$s.Arguments = " + psq(args),
    "$s.WorkingDirectory = " + psq(REPO_ROOT),
    fs.existsSync(ico) ? "$s.IconLocation = " + psq(ico) : "",
    "$s.Description = " + psq(APP_NAME),
    "$s.Save()"
  ].filter(Boolean).join("\n");

  const tmp = path.join(os.tmpdir(), "cds-shortcut-" + Date.now() + ".ps1");
  fs.writeFileSync(tmp, ps, "utf8");
  try {
    execFileSync("powershell", ["-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", tmp],
      { stdio: "ignore" });
  } finally {
    fs.rmSync(tmp, { force: true });
  }
}

/** Single-quote for PowerShell. */
function psq(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function version() {
  try { return require(path.join(REPO_ROOT, "package.json")).version || "1.0.0"; }
  catch (e) { return "1.0.0"; }
}

/* ── create ──────────────────────────────────────────────────────────────── */

/**
 * Write the launcher to the app menu, the Desktop and the project folder.
 * Never throws: a failed launcher must not fail `npm install`.
 */
function create() {
  const electron = electronBinary();
  const made = [];
  const failed = [];
  if (!electron) return { made, failed: ["Electron is not installed — run npm install first"] };
  if (!IS_MAC && !IS_WIN) return { made, failed: ["Launchers are only generated on macOS and Windows"] };

  const dirs = [appMenuDir(), desktopDir(), REPO_ROOT].filter(Boolean);
  for (const dir of dirs) {
    const dest = path.join(dir, APP_NAME + (IS_MAC ? ".app" : ".lnk"));
    try {
      fs.mkdirSync(dir, { recursive: true });
      if (IS_MAC) writeMacApp(dest, electron);
      else writeWinShortcut(dest, electron, quoteArg(REPO_ROOT));
      made.push(dest);
    } catch (err) {
      failed.push(dest + " — " + (err && err.message));
    }
  }
  return { made, failed };
}

function quoteArg(s) {
  return /\s/.test(s) ? '"' + s + '"' : s;
}

/* ── staleness ───────────────────────────────────────────────────────────── */

/**
 * True when a launcher exists but points at a different folder — i.e. the SE
 * moved or copied the project. Without this the launcher fails in a way that
 * looks like the app is broken rather than misplaced.
 */
function isStale() {
  const p = primaryLauncher();
  if (!p || !fs.existsSync(p)) return false;
  try {
    if (IS_MAC) {
      const script = fs.readFileSync(path.join(p, "Contents", "MacOS", "launcher"), "utf8");
      const m = script.match(/^REPO='([\s\S]*?)'$/m);
      return m ? m[1].replace(/'\\''/g, "'") !== REPO_ROOT : false;
    }
    // On Windows the target is Electron inside this repo's node_modules, so
    // comparing the shortcut's own working directory is enough.
    const out = execFileSync("powershell", ["-NoProfile", "-NonInteractive", "-Command",
      "(New-Object -ComObject WScript.Shell).CreateShortcut(" + psq(p) + ").WorkingDirectory"],
      { encoding: "utf8" });
    return out.trim() !== REPO_ROOT;
  } catch (e) {
    return false;
  }
}

/* ── start at login ──────────────────────────────────────────────────────── */

/*
 * The generated launcher is registered, never Electron's binary. Electron's own
 * app.setLoginItemSettings would show "Electron" in Login Items when running
 * from source, and on Windows would launch Electron with no app path at all.
 */
function osa(script, quiet) {
  return execFileSync("osascript", ["-e", script], {
    encoding: "utf8",
    // The idempotent delete below fails with -1728 whenever the item isn't
    // there, which is the normal case. Don't let that reach the log.
    stdio: quiet ? ["ignore", "pipe", "ignore"] : ["ignore", "pipe", "pipe"]
  });
}

function loginItemEnabled() {
  try {
    if (IS_MAC) {
      const names = osa('tell application "System Events" to get the name of every login item');
      return names.split(",").map((s) => s.trim()).includes(APP_NAME);
    }
    if (IS_WIN) {
      const dir = startupDir();
      return !!dir && fs.existsSync(path.join(dir, APP_NAME + ".lnk"));
    }
  } catch (e) {}
  return false;
}

function setLoginItem(enabled) {
  try {
    if (IS_MAC) {
      const app = primaryLauncher();
      if (!app || !fs.existsSync(app)) return false;
      // Remove first so the call is idempotent and can't stack duplicates.
      try { osa('tell application "System Events" to delete login item "' + APP_NAME + '"', true); } catch (e) {}
      if (enabled) {
        osa('tell application "System Events" to make login item at end with properties ' +
            '{path:"' + app + '", hidden:true, name:"' + APP_NAME + '"}');
      }
      return true;
    }
    if (IS_WIN) {
      const dir = startupDir();
      if (!dir) return false;
      const dest = path.join(dir, APP_NAME + ".lnk");
      if (enabled) {
        const electron = electronBinary();
        if (!electron) return false;
        fs.mkdirSync(dir, { recursive: true });
        // --hidden so a login launch goes straight to the tray, no window.
        writeWinShortcut(dest, electron, quoteArg(REPO_ROOT) + " --hidden");
      } else {
        fs.rmSync(dest, { force: true });
      }
      return true;
    }
  } catch (e) {}
  return false;
}

module.exports = {
  APP_NAME, REPO_ROOT,
  create, isStale, primaryLauncher, electronBinary,
  loginItemEnabled, setLoginItem,
  supported: IS_MAC || IS_WIN
};
